//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViscaCamLink.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViscaCamLink.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Camera {0} ähnelt.
        /// </summary>
        public static string CameraProfile_DefaultName {
            get {
                return ResourceManager.GetString("CameraProfile_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ip address ähnelt.
        /// </summary>
        public static string CameraProfile_Ip {
            get {
                return ResourceManager.GetString("CameraProfile_Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The ip address (version 4) must be in the following format: (0-255).(0-255).(0-255).(0-255) ähnelt.
        /// </summary>
        public static string CameraProfile_Ip_Invalid {
            get {
                return ResourceManager.GetString("CameraProfile_Ip_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string CameraProfile_Name {
            get {
                return ResourceManager.GetString("CameraProfile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name can not be empty ähnelt.
        /// </summary>
        public static string CameraProfile_Name_Invalid {
            get {
                return ResourceManager.GetString("CameraProfile_Name_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port ähnelt.
        /// </summary>
        public static string CameraProfile_Port {
            get {
                return ResourceManager.GetString("CameraProfile_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The port has to be a number between 0 and 65535 ähnelt.
        /// </summary>
        public static string CameraProfile_Port_Invalid {
            get {
                return ResourceManager.GetString("CameraProfile_Port_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ViscaCamLink ähnelt.
        /// </summary>
        public static string Common_AppTitle {
            get {
                return ResourceManager.GetString("Common_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saved ähnelt.
        /// </summary>
        public static string Common_Saved {
            get {
                return ResourceManager.GetString("Common_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string Compact_Close {
            get {
                return ResourceManager.GetString("Compact_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore ähnelt.
        /// </summary>
        public static string Compact_Maximize {
            get {
                return ResourceManager.GetString("Compact_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize ähnelt.
        /// </summary>
        public static string Compact_Minimize {
            get {
                return ResourceManager.GetString("Compact_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next camera profile ähnelt.
        /// </summary>
        public static string Compact_NextProfile {
            get {
                return ResourceManager.GetString("Compact_NextProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous camera profile ähnelt.
        /// </summary>
        public static string Compact_PrevProfile {
            get {
                return ResourceManager.GetString("Compact_PrevProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move ähnelt.
        /// </summary>
        public static string Compact_Tab_Movement {
            get {
                return ResourceManager.GetString("Compact_Tab_Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Presets ähnelt.
        /// </summary>
        public static string Compact_Tab_Presets {
            get {
                return ResourceManager.GetString("Compact_Tab_Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom ähnelt.
        /// </summary>
        public static string Compact_Tab_Zoom {
            get {
                return ResourceManager.GetString("Compact_Tab_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit address ähnelt.
        /// </summary>
        public static string Connection_Edit {
            get {
                return ResourceManager.GetString("Connection_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconnect ähnelt.
        /// </summary>
        public static string Connection_Reconnect {
            get {
                return ResourceManager.GetString("Connection_Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to connect ähnelt.
        /// </summary>
        public static string ConnectionStatus_Failed {
            get {
                return ResourceManager.GetString("ConnectionStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected ähnelt.
        /// </summary>
        public static string ConnectionStatus_Ok {
            get {
                return ResourceManager.GetString("ConnectionStatus_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trying to connect... ähnelt.
        /// </summary>
        public static string ConnectionStatus_Working {
            get {
                return ResourceManager.GetString("ConnectionStatus_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Control ähnelt.
        /// </summary>
        public static string Control_ContainerTitle {
            get {
                return ResourceManager.GetString("Control_ContainerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrease move speed ähnelt.
        /// </summary>
        public static string Control_DecreaseSpeed {
            get {
                return ResourceManager.GetString("Control_DecreaseSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Return to home position ähnelt.
        /// </summary>
        public static string Control_Home {
            get {
                return ResourceManager.GetString("Control_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase move speed ähnelt.
        /// </summary>
        public static string Control_IncreaseSpeed {
            get {
                return ResourceManager.GetString("Control_IncreaseSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click and drag to pan/tilt ähnelt.
        /// </summary>
        public static string Control_MousePan {
            get {
                return ResourceManager.GetString("Control_MousePan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not set ähnelt.
        /// </summary>
        public static string HotKey_NotSet {
            get {
                return ResourceManager.GetString("HotKey_NotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press a key… ähnelt.
        /// </summary>
        public static string HotKey_PressKey {
            get {
                return ResourceManager.GetString("HotKey_PressKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Camera Profile ähnelt.
        /// </summary>
        public static string HotKeyAction_CameraProfileNext {
            get {
                return ResourceManager.GetString("HotKeyAction_CameraProfileNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous Camera Profile ähnelt.
        /// </summary>
        public static string HotKeyAction_CameraProfilePrevious {
            get {
                return ResourceManager.GetString("HotKeyAction_CameraProfilePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Down ähnelt.
        /// </summary>
        public static string HotKeyAction_MoveDown {
            get {
                return ResourceManager.GetString("HotKeyAction_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Left ähnelt.
        /// </summary>
        public static string HotKeyAction_MoveLeft {
            get {
                return ResourceManager.GetString("HotKeyAction_MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Right ähnelt.
        /// </summary>
        public static string HotKeyAction_MoveRight {
            get {
                return ResourceManager.GetString("HotKeyAction_MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Up ähnelt.
        /// </summary>
        public static string HotKeyAction_MoveUp {
            get {
                return ResourceManager.GetString("HotKeyAction_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset {0} ähnelt.
        /// </summary>
        public static string HotKeyAction_Preset {
            get {
                return ResourceManager.GetString("HotKeyAction_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Preset Group ähnelt.
        /// </summary>
        public static string HotKeyAction_PresetGroupNext {
            get {
                return ResourceManager.GetString("HotKeyAction_PresetGroupNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous Preset Group ähnelt.
        /// </summary>
        public static string HotKeyAction_PresetGroupPrevious {
            get {
                return ResourceManager.GetString("HotKeyAction_PresetGroupPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom In ähnelt.
        /// </summary>
        public static string HotKeyAction_ZoomIn {
            get {
                return ResourceManager.GetString("HotKeyAction_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom Out ähnelt.
        /// </summary>
        public static string HotKeyAction_ZoomOut {
            get {
                return ResourceManager.GetString("HotKeyAction_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch (German) ähnelt.
        /// </summary>
        public static string Language_German {
            get {
                return ResourceManager.GetString("Language_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System based ähnelt.
        /// </summary>
        public static string Language_System {
            get {
                return ResourceManager.GetString("Language_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ViscaCamLink has been reinstalled as a per-user app and will keep itself up to date automatically.
        ///
        ///The previous system-wide installation is no longer needed. You can remove it now — or later via Windows Settings → Apps. ähnelt.
        /// </summary>
        public static string Migration_Body {
            get {
                return ResourceManager.GetString("Migration_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skip for now ähnelt.
        /// </summary>
        public static string Migration_SkipButton {
            get {
                return ResourceManager.GetString("Migration_SkipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to ViscaCamLink 1.0.0 ähnelt.
        /// </summary>
        public static string Migration_Title {
            get {
                return ResourceManager.GetString("Migration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall old version ähnelt.
        /// </summary>
        public static string Migration_UninstallButton {
            get {
                return ResourceManager.GetString("Migration_UninstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available soon! ähnelt.
        /// </summary>
        public static string Options_Availability {
            get {
                return ResourceManager.GetString("Options_Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string Options_General {
            get {
                return ResourceManager.GetString("Options_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use global hotkeys (active even when the app is not focused) ähnelt.
        /// </summary>
        public static string Options_GlobalHotKeys {
            get {
                return ResourceManager.GetString("Options_GlobalHotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action ähnelt.
        /// </summary>
        public static string Options_HotKeyAction {
            get {
                return ResourceManager.GetString("Options_HotKeyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key ähnelt.
        /// </summary>
        public static string Options_HotKeyBinding {
            get {
                return ResourceManager.GetString("Options_HotKeyBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hotkeys ähnelt.
        /// </summary>
        public static string Options_Hotkeys {
            get {
                return ResourceManager.GetString("Options_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose the display language  ähnelt.
        /// </summary>
        public static string Options_LanguageSelection {
            get {
                return ResourceManager.GetString("Options_LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use compact view when minimizing ähnelt.
        /// </summary>
        public static string Options_MinimizeToCompactWindow {
            get {
                return ResourceManager.GetString("Options_MinimizeToCompactWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Numpad preset layout ähnelt.
        /// </summary>
        public static string Options_NumpadLayout {
            get {
                return ResourceManager.GetString("Options_NumpadLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart needed ähnelt.
        /// </summary>
        public static string Options_RestartNeeded {
            get {
                return ResourceManager.GetString("Options_RestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose the app theme ähnelt.
        /// </summary>
        public static string Options_ThemeSelection {
            get {
                return ResourceManager.GetString("Options_ThemeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use multiple camera profiles ähnelt.
        /// </summary>
        public static string Options_UseMultipleCameras {
            get {
                return ResourceManager.GetString("Options_UseMultipleCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use preset groups ähnelt.
        /// </summary>
        public static string Options_UsePresetGroups {
            get {
                return ResourceManager.GetString("Options_UsePresetGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Faulty camera status ähnelt.
        /// </summary>
        public static string PowerStatus_Error {
            get {
                return ResourceManager.GetString("PowerStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Camera active ähnelt.
        /// </summary>
        public static string PowerStatus_On {
            get {
                return ResourceManager.GetString("PowerStatus_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Camera on standby ähnelt.
        /// </summary>
        public static string PowerStatus_Standby {
            get {
                return ResourceManager.GetString("PowerStatus_Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Camera is switching on... ähnelt.
        /// </summary>
        public static string PowerStatus_SwitchingOn {
            get {
                return ResourceManager.GetString("PowerStatus_SwitchingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Camera is switching into standby... ähnelt.
        /// </summary>
        public static string PowerStatus_SwitchingToStandby {
            get {
                return ResourceManager.GetString("PowerStatus_SwitchingToStandby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown camera status ähnelt.
        /// </summary>
        public static string PowerStatus_Unknown {
            get {
                return ResourceManager.GetString("PowerStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        public static string PresetGroup_DefaultName {
            get {
                return ResourceManager.GetString("PresetGroup_DefaultName", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group {0} ähnelt.
        /// </summary>
        public static string PresetGroup_NewName {
            get {
                return ResourceManager.GetString("PresetGroup_NewName", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose a slot ähnelt.
        /// </summary>
        public static string Presets_ChooseSlot {
            get {
                return ResourceManager.GetString("Presets_ChooseSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Presets ähnelt.
        /// </summary>
        public static string Presets_ContainerTitle {
            get {
                return ResourceManager.GetString("Presets_ContainerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save current position as preset ähnelt.
        /// </summary>
        public static string Presets_Save {
            get {
                return ResourceManager.GetString("Presets_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Control panel ähnelt.
        /// </summary>
        public static string Sidebar_ControlPanel {
            get {
                return ResourceManager.GetString("Sidebar_ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string Sidebar_Options {
            get {
                return ResourceManager.GetString("Sidebar_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Presets panel ähnelt.
        /// </summary>
        public static string Sidebar_PresetsPanel {
            get {
                return ResourceManager.GetString("Sidebar_PresetsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom panel ähnelt.
        /// </summary>
        public static string Sidebar_ZoomPanel {
            get {
                return ResourceManager.GetString("Sidebar_ZoomPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System based ähnelt.
        /// </summary>
        public static string Theme_System {
            get {
                return ResourceManager.GetString("Theme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changelog ähnelt.
        /// </summary>
        public static string Updater_Changelog {
            get {
                return ResourceManager.GetString("Updater_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current: ähnelt.
        /// </summary>
        public static string Updater_CurrentVersion {
            get {
                return ResourceManager.GetString("Updater_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download failed: ähnelt.
        /// </summary>
        public static string Updater_DownloadError {
            get {
                return ResourceManager.GetString("Updater_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading... ähnelt.
        /// </summary>
        public static string Updater_Downloading {
            get {
                return ResourceManager.GetString("Updater_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New version available! ähnelt.
        /// </summary>
        public static string Updater_NewVersionAvailable {
            get {
                return ResourceManager.GetString("Updater_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retry ähnelt.
        /// </summary>
        public static string Updater_Retry {
            get {
                return ResourceManager.GetString("Updater_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        public static string Updater_Update {
            get {
                return ResourceManager.GetString("Updater_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom ähnelt.
        /// </summary>
        public static string Zoom_ContainerTitle {
            get {
                return ResourceManager.GetString("Zoom_ContainerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrease zoom speed ähnelt.
        /// </summary>
        public static string Zoom_DecreaseSpeed {
            get {
                return ResourceManager.GetString("Zoom_DecreaseSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase zoom speed ähnelt.
        /// </summary>
        public static string Zoom_IncreaseSpeed {
            get {
                return ResourceManager.GetString("Zoom_IncreaseSpeed", resourceCulture);
            }
        }
    }
}
