//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViscaCamLink.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViscaCamLink.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViscaCamLink.
        /// </summary>
        public static string Common_AppTitle {
            get {
                return ResourceManager.GetString("Common_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Common_Saved {
            get {
                return ResourceManager.GetString("Common_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit address.
        /// </summary>
        public static string Connection_Edit {
            get {
                return ResourceManager.GetString("Connection_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string Connection_Reconnect {
            get {
                return ResourceManager.GetString("Connection_Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect.
        /// </summary>
        public static string ConnectionStatus_Failed {
            get {
                return ResourceManager.GetString("ConnectionStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string ConnectionStatus_Ok {
            get {
                return ResourceManager.GetString("ConnectionStatus_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to connect....
        /// </summary>
        public static string ConnectionStatus_Working {
            get {
                return ResourceManager.GetString("ConnectionStatus_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string Control_ContainerTitle {
            get {
                return ResourceManager.GetString("Control_ContainerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease move speed.
        /// </summary>
        public static string Control_DecreaseSpeed {
            get {
                return ResourceManager.GetString("Control_DecreaseSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to home position.
        /// </summary>
        public static string Control_Home {
            get {
                return ResourceManager.GetString("Control_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase move speed.
        /// </summary>
        public static string Control_IncreaseSpeed {
            get {
                return ResourceManager.GetString("Control_IncreaseSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch (German).
        /// </summary>
        public static string Language_German {
            get {
                return ResourceManager.GetString("Language_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System based.
        /// </summary>
        public static string Language_System {
            get {
                return ResourceManager.GetString("Language_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available soon!.
        /// </summary>
        public static string Options_Availability {
            get {
                return ResourceManager.GetString("Options_Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Options_General {
            get {
                return ResourceManager.GetString("Options_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the display language .
        /// </summary>
        public static string Options_LanguageSelection {
            get {
                return ResourceManager.GetString("Options_LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart needed.
        /// </summary>
        public static string Options_RestartNeeded {
            get {
                return ResourceManager.GetString("Options_RestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faulty camera status.
        /// </summary>
        public static string PowerStatus_Error {
            get {
                return ResourceManager.GetString("PowerStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera active.
        /// </summary>
        public static string PowerStatus_On {
            get {
                return ResourceManager.GetString("PowerStatus_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera on standby.
        /// </summary>
        public static string PowerStatus_Standby {
            get {
                return ResourceManager.GetString("PowerStatus_Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera is switching on....
        /// </summary>
        public static string PowerStatus_SwitchingOn {
            get {
                return ResourceManager.GetString("PowerStatus_SwitchingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera is switching into standby....
        /// </summary>
        public static string PowerStatus_SwitchingToStandby {
            get {
                return ResourceManager.GetString("PowerStatus_SwitchingToStandby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown camera status.
        /// </summary>
        public static string PowerStatus_Unknown {
            get {
                return ResourceManager.GetString("PowerStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a slot.
        /// </summary>
        public static string Presets_ChooseSlot {
            get {
                return ResourceManager.GetString("Presets_ChooseSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        public static string Presets_ContainerTitle {
            get {
                return ResourceManager.GetString("Presets_ContainerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current position as preset.
        /// </summary>
        public static string Presets_Save {
            get {
                return ResourceManager.GetString("Presets_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel.
        /// </summary>
        public static string Sidebar_ControlPanel {
            get {
                return ResourceManager.GetString("Sidebar_ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Sidebar_Options {
            get {
                return ResourceManager.GetString("Sidebar_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets panel.
        /// </summary>
        public static string Sidebar_PresetsPanel {
            get {
                return ResourceManager.GetString("Sidebar_PresetsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom panel.
        /// </summary>
        public static string Sidebar_ZoomPanel {
            get {
                return ResourceManager.GetString("Sidebar_ZoomPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string Updater_Changelog {
            get {
                return ResourceManager.GetString("Updater_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current:.
        /// </summary>
        public static string Updater_CurrentVersion {
            get {
                return ResourceManager.GetString("Updater_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// </summary>
        public static string Updater_NewVersionAvailable {
            get {
                return ResourceManager.GetString("Updater_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Updater_Update {
            get {
                return ResourceManager.GetString("Updater_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string Zoom_ContainerTitle {
            get {
                return ResourceManager.GetString("Zoom_ContainerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease zoom speed.
        /// </summary>
        public static string Zoom_DecreaseSpeed {
            get {
                return ResourceManager.GetString("Zoom_DecreaseSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase zoom speed.
        /// </summary>
        public static string Zoom_IncreaseSpeed {
            get {
                return ResourceManager.GetString("Zoom_IncreaseSpeed", resourceCulture);
            }
        }
    }
}
